### ISSUE TITLE
How about using ASCII color to render?

### ISSUE THREAD

**Issue by kevinbird61** [billcccheng/instagram-terminal-news-feed#4]
It's a fun project!
Maybe it can add ascii color code  on it ?
Like this nyancat project : https://github.com/klange/nyancat

**Comment by billcccheng** [comment]
Working on it now
https://github.com/billcccheng/instagram-terminal-news-feed/tree/display-color

**Comment by billcccheng** [comment]
Finished this feature. Please pull the latest code. Thanks!
